### ISSUE TITLE
ERROR: An error occurred signing the manifest. Check that all signature parameters are correct.

### ISSUE THREAD

**Issue by Marcus222222** [mansellan/clickonce#47]
We have an issues that is not possible to reproduce.

Once in a while we get an error thrown. "ERROR: An error occurred signing the manifest. Check that all signature parameters are correct"

The thing is that the parameters are correct and the same as the previous build that worked.

![image](https://user-images.githubusercontent.com/89140168/129898254-84e6e987-afda-421c-9ec3-7325e687dac0.png)

Any suggestions ?
Best regards
Marcus Pettersson

**Comment by mansellan** [comment]
Hi,

Not that I can think of. Intermittant bugs are notoriously difficult to debug, and I don't actually use signing in any of my builds. I'm relying on the CodeSigning repo to handle certificates.

That said, I'm happy to look into it. Is the certificate you're using installed on the server (located by thumbprint) or added as an Azure DevOps secure file?

**Comment by Marcus222222** [comment]
Hi,

The certificate is added as an azure devops secure file.

Thanks!
Regards
Marcus

**Comment by mansellan** [comment]
Really sorry, I'm going to have to close this as I can't repro it. Since I uploaded our corporate certificate, we've had dozens of builds without seeing this. I can only assume it's something unusual with your environment.

If you like, you can remove signing from the ClickOnce task and add an explicit Code Signing task - this task just defers to it.

Sorry, and I hope you find a solution.
